export const FADEINANIMATION = [
  "animate-fadeInSlideUp",
  "animate-fadeInSlideUp ani-delay-100",
  "animate-fadeInSlideUp ani-delay-200",
  "animate-fadeInSlideUp ani-delay-300",
  "animate-fadeInSlideUp ani-delay-400",
  "animate-fadeInSlideUp ani-delay-500",
  "animate-fadeInSlideUp ani-delay-600",
  "animate-fadeInSlideUp ani-delay-700",
  "animate-fadeInSlideUp ani-delay-800",
  "animate-fadeInSlideUp ani-delay-900",
  "animate-fadeInSlideUp ani-delay-1000",
  "animate-fadeInSlideUp ani-delay-1100",
  "animate-fadeInSlideUp ani-delay-1200",
  "animate-fadeInSlideUp ani-delay-1300",
  "animate-fadeInSlideUp ani-delay-1400",
  "animate-fadeInSlideUp ani-delay-1500",
  "animate-fadeInSlideUp ani-delay-1600",
  "animate-fadeInSlideUp ani-delay-1700",
  "animate-fadeInSlideUp ani-delay-1800",
  "animate-fadeInSlideUp ani-delay-1900",
  "animate-fadeInSlideUp ani-delay-2000",
];
